version: '3.7'

networks:
  backend:
#    uses bridge driver by default
    name: backend

services:
  technical-notes:
    image: dpratt747/technical_notes:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST_NAME=${POSTGRES_HOST_NAME}
      - APPLICATION_HOST_NAME=${APPLICATION_HOST_NAME}
      - "JAVA_TOOL_OPTIONS:-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    ports:
      - "${APPLICATION_EXPOSED_PORT}:${INTERNAL_APPLICATION_PORT}"
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    networks:
      - backend
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
