version: '3.7'
services:

  technical-notes:
    image: dpratt747/technical_notes:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      - ${POSTGRES_DB}
      - ${POSTGRES_PASSWORD}
      - ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
