version: '3.7'

networks:
  backend:
#    uses bridge driver by default
    name: backend

services:
  technical-notes:
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    image: dpratt747/technical_notes:latest
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "0:5005"

  postgres:
    image: postgres:latest
    networks:
      - backend
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
#      to make this non accessible outside the network remove the exposed port so the definition look like: - "5432"
      - "${POSTGRES_EXPOSED_PORT}:5432"
